config {
    type: "view",
    description: "Join common columns into a single table along with cloud ID",
    name: "00_azure_std",
    schema: "20_Silver"
}

SELECT
  JSON_VALUE(metadata_json, '$.cloud_name') AS cloud_name,
  JSON_VALUE(metadata_json, '$.ingestion_date') AS ingestion_date,
  ResourceLocation AS zone,
  CustomerTenantId AS billing_account_id,
  BillingCurrencyCode AS billing_currency,
  CAST(ServicePeriodEndDate AS datetime) AS billing_period_end_date,
  CAST(ServicePeriodStartDate AS datetime) AS billing_period_start_date,
  PublisherType AS publisher_charge,
  ConsumedService AS charge_category,
  ServiceFamily AS charge_description,
  EXTRACT(month
  FROM
    Date) AS invoice_month,
  CAST(CostInBillingCurrency AS NUMERIC) AS billed_cost,
  CAST(CASE
      WHEN EffectivePrice != UnitPrice THEN (EffectivePrice * Quantity)
      ELSE (UnitPrice * Quantity)
  END
    AS NUMERIC) AS effective_price,
  CAST((UnitPrice * Quantity) AS NUMERIC) AS list_price,
  CAST(Quantity AS NUMERIC) AS usage_amount,
  UnitOfMeasure AS usage_unit,
  UnitOfMeasure AS pricing_unit,
  ResourceLocation AS region,
  MeterId AS resource_id,
  ConsumedService AS service_category,
  Product AS product_code,
  MeterId AS sku_id,
  SubscriptionGuid AS account,
  SubscriptionName AS account_name,
  AdditionalInfo AS additional_info,
  ResourceGroup AS resource_group
FROM
  ${ref("10_union_azure")}
