config {
    type: "view",
    description: "Join common columns into a single table along with cloud ID",
    name: "00_aws_std",
    schema: "20_Silver"
}

SELECT
  JSON_VALUE(metadata_json, '$.cloud_name') AS cloud_name,
  JSON_VALUE(metadata_json, '$.ingestion_date') AS ingestion_date,
  IFNULL(line_item_availability_zone,"Gobal") AS zone,
  bill_payer_account_id AS billing_account_id,
  line_item_currency_code AS billing_currency,
  CAST(line_item_usage_start_date AS datetime) AS billing_period_end_date,
  CAST(line_item_usage_end_date AS datetime) AS billing_period_start_date,
  "Amazon" AS publisher_charge,
  line_item_line_item_type AS charge_category,
  line_item_line_item_description AS charge_description,
  EXTRACT(month
  FROM
    bill_billing_period_end_date) AS invoice_month,
  CAST(line_item_blended_rate AS NUMERIC) AS billed_cost,
  CAST(line_item_unblended_rate AS NUMERIC) * CAST(line_item_usage_amount AS NUMERIC) AS effective_price,
  CAST(line_item_unblended_rate AS NUMERIC) AS list_price,
  CAST(line_item_usage_amount AS NUMERIC) AS usage_amount,
  pricing_term AS usage_unit,
  pricing_unit AS pricing_unit,
  product_region_code AS region,
  line_item_product_code AS resource_id,
  product_servicecode AS service_category,
  line_item_product_code AS product_code,
  product_sku AS sku_id,
  line_item_usage_account_id AS account,
  line_item_usage_account_name AS account_name,
  "na" AS additional_info,
  resource_tags_key.`key_value`[SAFE_OFFSET(0)].value AS resource_group
FROM
  ${ref("10_union_aws")}
