config {
    type: "view",
    description: "Join common columns into a single table along with cloud ID",
    name: "00_gcp_std",
    schema: "20_Silver"
}

SELECT
  JSON_VALUE(metadata_json, '$.cloud_name') AS cloud_name,
  JSON_VALUE(metadata_json, '$.ingestion_date') AS ingestion_date,
  location_zone AS zone,
  billing_account_id AS billing_account_id,
  currency AS billing_currency,
  CAST(usage_start_time AS datetime) AS billing_period_end_date,
  CAST(usage_end_time AS datetime) AS billing_period_start_date,
  invoice_publisher_type AS publisher_charge_charge,
  cost_type AS charge_category,
  sku_description AS charge_description,
  CAST(invoice_month AS INT) AS invoice_month,
  CAST(cost_at_list AS NUMERIC) AS billed_cost,
  CAST(price_effective_price AS NUMERIC) AS effective_price,
  /*check if same as cost_at_list*/
  CAST(cost_at_list AS NUMERIC) AS list_price,
  CAST(usage_amount AS NUMERIC) AS usage_amount,
  usage_unit AS usage_unit,
  price_unit AS pricing_unit,
  location_region AS region,
  resource_global_name AS resource_id,
  service_description AS service_category,
  /*check if same as sku.description*/
  sku_description AS product_code,
  sku_id AS sku_id,
  project_id AS account,
  project_name AS account_name,
  adjustment_info_description AS additional_info,
  tags_json AS resource_group
FROM
  ${ref("10_union_gcp")}
