config {
    type: "incremental",
    schema: "30_Gold",
    name: "agg_incremental",
    description: "Incremental data table",
    uniqueKey: ["invoice_month", "cloud_name", "billing_account_id", "service_category", "product_code"]
}

SELECT
  invoice_month,
  cloud_name,
  billing_account_id,
  service_category,
  product_code,
  SUM(billed_cost) AS total_billed_cost
FROM
  ${ref("20_transformation")} ${when(incremental(), `WHERE ingestion_date > (SELECT MAX(ingestion_date) FROM ${self()})`)}
GROUP BY
  invoice_month,
  cloud_name,
  billing_account_id,
  service_category,
  product_code
