
config {
    type: "table",
    description: "Deduplicate Azure billing data",
    schema: "20_Silver",
    name: "20_00_azure_dedup",
    dependencies: ["00_azure_std"]
}

SELECT
  * EXCEPT (row_num)
FROM
(
  SELECT *, ROW_NUMBER() OVER(
        PARTITION BY
          invoice_month,
          billing_account_id,
          resource_id,
          sku_id,
          billing_period_start_date,
          billing_period_end_date,
          account,
          billed_cost,
          effective_price,
          charge_category,
          billing_currency
    ORDER BY ingestion_date DESC
  ) AS row_num
 FROM
  ${ref("00_azure_std")}
)
WHERE
row_num = 1